name: Build Lynx

on:
  push:
    branches:
      - dev # You can change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [macos-x64, windows-x64, linux-x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust the Node.js version if needed (18 preferred)

      - name: Install dependencies
        run: npm install

      - name: Install ncc and pkg
        run: npm install -g @vercel/ncc pkg

      - name: Build Lynx for ${{ matrix.os }}
        run: |
          ncc build -o build/lib ./index.js
          pkg --targets node18-${{ matrix.os }} -o build/lynx-${{ matrix.os }} ./build/lib/index.js

      - name: Set up Git
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"

      - name: Get package version
        id: get-version
        run: echo ::set-output name=version::$(node -e "console.log(require('./package.json').version)")

      - name: Move built binaries to versioned directory
        run: |
          mkdir -p build/${{ steps.get-version.outputs.version }}
          mv build/lynx-* build/${{ steps.get-version.outputs.version }}/

      - name: Push Builds
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'dev' # Change to the current target branch (main)
          commit-message: 'Publish Builds' # Customize the commit message
          force-add: 'true'
          files: |
            build/linux-x64/
            build/macos-x64/
            build/windows-x64/
          name: 'Lynx Bot' # Customize the committer's name
          email: 'info@lynx.dev' # Customize the committer's email
